### PR TITLE
More fixes for the Google Collab notebooks

### PR DESCRIPTION
**Pull request by InnocentBug**
Curiously, there is a problem with the `plum.dispatch` of constructors.
If I specify arguments with keywords, a constructor is called that doesn't match any on the ones specified and I get basically an empty `UmbrellaIntegration` instance.
That is weird, and potentially problematic. But I don't know how to fix it.

Not using keywords in this case fixed the problem.

### CODE REVIEW

**Comment by InnocentBug** [comment]
https://github.com/beartype/plum/issues/40

This is underlying issue behind what we see here.

**Review by pabloferz — APPROVED** [review]

**Comment by pabloferz** [comment]
The issue now is the newest version of `plum`. I need to fix that separately. This looks fine to me so I will go ahead and merge.

**Comment by pabloferz** [comment]
Just to let some breadcrumbs here. Everything should work fine by installing a plum version <2. E.g., `pip install "plum-dispatch<2"`

**Pull request merged**
