### PR TITLE
Specialize distance when using groups

### PR DESCRIPTION
**Pull request by pabloferz**

### CODE REVIEW

**Comment by InnocentBug** [comment]
I tried in the notebook.
And it didn't solve the issue for me :(

**Comment by pabloferz** [comment]
Let me look at it again. Are we sure that #163 introduced the change in behaviour?

**Comment by pabloferz** [comment]
I added a test comparing the result when using groups vs when not and they seem to give the same result and it seems to be working. What are the differences you are seeing with this PR?

**Comment by InnocentBug** [comment]
Ok, I double checked. Now it works.

**Review by InnocentBug — APPROVED** [review]

**Pull request merged**
