### PR TITLE
New hoomd backend

### PR DESCRIPTION
**Pull request by InnocentBug**
Works with the new hoomd-dlext implementation.

### CODE REVIEW

**Comment by InnocentBug** [comment]
it works :partying_face:

**Comment by InnocentBug** [comment]
we can and should merge this now

**Comment by pabloferz** [comment]
Are the containers ready?

**Comment by InnocentBug** [comment]
yes, they are

I initiated it yesterday and the test would fail otherwise

**Review by pabloferz — APPROVED** [review]

**Pull request merged**
