### PR TITLE
Setup.py to install pysages

### PR DESCRIPTION
**Pull request by InnocentBug**

### CODE REVIEW

**Comment by InnocentBug** [comment]
Let's talk about it tomorrow. I have some questions.

**Comment by InnocentBug** [comment]
Do you have a reason, why you don't like versioneer?
I don't really know what you intend with a github bot, but versioneer running at install time can do so much more.
It can especially track and notice changes that are not a full new version, which at least helps me significantly when tracking other peoples errors.

**Comment by pabloferz** [comment]
I see what you mean. It's just that versioneer feels too bloated. Would something like https://github.com/jbweston/miniver would work instead?

**Review by pabloferz — APPROVED** [review]

**Comment by pabloferz** [comment]
Let's merge and see how it goes. We can always fix any issue later.

**Comment by InnocentBug** [comment]
I address the failing test in #15

**Pull request merged**
