### PR TITLE
Fix compatibility with plum>=2

### PR DESCRIPTION
**Pull request by pabloferz**
`plum >=2` brings some breaking changes which cause tests to fail right now. This PR provides a compatibility layer to support the newest plum version while preserving compatibility with `plum <2`.

/trunk merge

### CODE REVIEW

**Review by InnocentBug — DISMISSED** [review]

**Comment by pabloferz** [comment]
`plum >2` breaks the interplay of docstrings with Sphinx (https://github.com/beartype/plum/issues/75). We will have to wait for another release of plum that fixes these issues to merge this. For the time being we can move on with #259.

**Review by InnocentBug — DISMISSED** [review]

**Comment by pabloferz** [comment]
I have commented out the documentation for all specializations of `run` for now. https://github.com/beartype/plum/issues/75 seems to be partially solved, but it doesn't work yet the way it's supposed to.

I'm proposing to fix the documentations issues in a later PR.

**Review by gustavor101 — APPROVED** [review]

**Pull request merged**
