### PR TITLE
Split methods in separate files

### PR DESCRIPTION
**Pull request by InnocentBug**
This splits the methods into separate files, with two advantages beyond cleaning.
1) hide inner workings of the methods from the user (`_` prefix) for the functions.
2) easier extension to more methods, just add a separate file for the methods.

Let me know what you think about the direction here.

I haven't tested if it works yet.

### CODE REVIEW

**Comment by InnocentBug** [comment]
At the moment, the proposed change breaks existing scripts, because I do not expose the method classes in the `pysages.ssages.methods` namespace.
If backwards compatibility is wanted, we can expose the classes in the namespace though.

**Comment by pabloferz** [comment]
I was thinking on moving what you have in `__init__.py` into a `core.py` file and using `__init__.py` only to explicitly export the default, visible symbols.

We can get away breaking the API for now as the is no official release yet.

**Comment by InnocentBug** [comment]
I agree, I also thought about moving the contents of init into a separate file and importing only in init.
Let me push that.

**Review by pabloferz — APPROVED** [review]
LGTM

**Pull request merged**
