### PR TITLE
Move linters config files to .trunk/config

### PR DESCRIPTION
**Pull request by pabloferz**
I'd like to have less clutter on the file structure shown in GH, and this is supported by trunk.

### CODE REVIEW

**Review by InnocentBug — CHANGES_REQUESTED** [review]
Generally, good plan! It's a feature of trunk that they added recently.

However, I think the `.readthedocs.yaml` needs to stay where it was.
That is a file for readthedocs, not trunk or linting.

**Comment by InnocentBug** [comment]
Please don't force push, after I start reviewing.
Makes it very hard for me to keep track of what you changed after my comment.
Thanks

**Comment by pabloferz** [comment]
I did force push just because of the way my local configuration is setup, but did not modify the commit structure, you should be able to see the new changes without any issue.

**Review by InnocentBug — APPROVED** [review]

**Pull request merged**
