### PR TITLE
add basic things for merge-q

### PR DESCRIPTION
**Pull request by InnocentBug**

### CODE REVIEW

**Comment by InnocentBug** [comment]
As soon as you approve, this should automatically progress in the merge queue and be merged, once the tests ran all again (and passed.)

**Review by pabloferz — DISMISSED** [review]

**Comment by InnocentBug** [comment]
Please don't work manually.
I am trying to figure out, why the merge queue doesn't do it automatically.

**Comment by InnocentBug** [comment]
I will have to figure out why the merge queue can't run the tests right now.
That probably requires talking to the trunk people.

**Comment by InnocentBug** [comment]
trunk released a new version today.
I upgraded the branch, maybe it is working now.

**Review by pabloferz — APPROVED** [review]

**Pull request merged**
