### PR TITLE
Fix NACL test with new FF URL

### LINKED ISSUE #209: Two files are almost the same.
`examples/openmm/metad/nacl/nacl.py`
and 
`examples/openmm/metad/nacl/nacl-displacement.py`
are almost the same file.

Can maybe one of them import stuff from the other one.
Maintance seems hard here.

### PR DESCRIPTION
**Pull request by InnocentBug**
Also consolidate the two NACL files.
Close #209

### CODE REVIEW

**Review by pabloferz — APPROVED** [review]

**Review by ricalessandri — COMMENTED** [review]
LGTM. Is the test failing, though?

Also, should we get rid of these commented-out lines:
https://github.com/SSAGESLabs/PySAGES/blob/b33aae291e1c8aba82e751abf59c7c32e119d2b3/examples/openmm/metad/nacl/nacl.py#L85-L86

**Comment by InnocentBug** [comment]
Sure, let's get rid of these lines

**Comment by InnocentBug** [comment]
Yes, it should work now.
And it works locally on my machine.

The error, I am getting in the test is HTTP 400, while before we got 404 for the missing file.
I am not sure, why we are getting 400 now. Seems like an odd error for me.
I am ready to locally stores this input file and not download it from the web everytime.

What do you think?

**Comment by pabloferz** [comment]
HTTP 400 is a bad request, but this works locally, so we can ignore this for now. Can we update the corresponding Colab notebooks? I just remembered those also were written with the previous URL

**Comment by InnocentBug** [comment]
Ok, I fixed the notebook now as well.

(There were more issues)

Howver @pabloferz , I also noticed that OpenMM doesn't work in the notebooks right now.
Is OpenMM missing from the notebook env now?

**Comment by InnocentBug** [comment]
Also, I would really like for the test to not fail anymore.
I am trying to setup merge queues for us and it won't merge if we have failing tests.

That's where my locally stored forcefield idea is coming from.

**Comment by InnocentBug** [comment]
Ahh, it doesn't work.

**Review by pabloferz — APPROVED** [review]

**Pull request merged**
