### PR TITLE
Make parametric Result types serializable

### PR DESCRIPTION
**Pull request by pabloferz**
Should help with #172. We might want to add tests for serializing parametric `Result` types (e.g. `Result[ANN]`)

### CODE REVIEW

**Review by InnocentBug — APPROVED** [review]

**Comment by ricalessandri** [comment]
Thanks - I'll try this out tomorrow.

**Comment by ricalessandri** [comment]
Ok, I tested this branch (version: `0.3.1.dev65+g3279c98`) for pickling (like in #172 ) and ANN/CFF/SpectralABF did not work, I get something like:
```
Traceback (most recent call last):
  File "adp_ANN.py", line 140, in <module>
    main(sys.argv[1:])
  File "adp_ANN.py", line 133, in main
    pickle.dump( result, open("result.pickle", "wb") )
AttributeError: Can't pickle local object 'analyze.<locals>.build_fes_fn.<locals>.fes_fn'
```

**Comment by pabloferz** [comment]
Are you pickling the `raw_result` or the `result`? (it looks like the latter). This patch only helps with making the results form `pysages.run` serializable.

**Review by ricalessandri — APPROVED** [review]
You're right, I was pickling the `results`. Pickling the `raw_result`, e.g.:
```
    raw_result = pysages.run(method, generate_simulation, args.time_steps)
    pickle.dump( raw_result, open("raw_result.pickle", "wb") )
```
works! I checked ANN, CFF, SpectralABF.

**Pull request merged**
