### PR TITLE
Add GeM CV

### PR DESCRIPTION
**Pull request by pabloferz**
Accidentally closed #231. Reopening on top #240 (so tests pass).

Original PR description:

> Implementation of the Geometry Matching (GeM) Local Order Metric (LOM). The algorithm enabling the measurement of order in the neighborhood of an atomic or molecular site is described in [Martelli2018](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.97.064105).

CC: @maggiezimon

### CODE REVIEW

**Comment by maggiezimon** [comment]
@pabloferz I can see that the `test_pickle.py` is failing because there is no `COLVAR_ARGS` specified for GeM. Do you need any help?

**Comment by pabloferz** [comment]
If tests pass, this should be ready, I did some modifications on the , but I have validated them.

Sorry for the long delay here @maggiezimon.

**Comment by maggiezimon** [comment]
@pabloferz I saw your changes. Thank you for your help.

**Comment by pabloferz** [comment]
@maggiezimon, if you are OK with this, can you do `Files changed` > `Review changes` > `Approve`?

**Review by maggiezimon — APPROVED** [review]

**Comment by pabloferz** [comment]
Thanks again for this!

**Pull request merged**
